"""A small Snake game built with the Arcade library. Generated by Codex

Run with:
    python snake.py
"""

import random

import arcade


SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_TITLE = "Snake"

CELL_SIZE = 20
SCORE_BAR_HEIGHT = 40
GRID_WIDTH = SCREEN_WIDTH // CELL_SIZE
GRID_HEIGHT = (SCREEN_HEIGHT - SCORE_BAR_HEIGHT) // CELL_SIZE
MOVE_INTERVAL = 0.12

BLACK = (0, 0, 0)
GREEN = (0, 220, 0)
RED = (220, 0, 0)
WHITE = (255, 255, 255)
GRAY = (150, 150, 150)

SNAKE_COLORS = [
    ("Green", GREEN, 0),
    ("Blue", (40, 130, 255), 3),
    ("Purple", (190, 70, 220), 6),
    ("Gold", (255, 180, 0), 10),
]
APPLE_COLORS = [
    ("Red", RED, 0),
    ("Orange", (255, 120, 20), 3),
    ("Pink", (255, 70, 150), 6),
    ("Cyan", (0, 210, 220), 10),
]


class SnakeGame(arcade.Window):
    """The main game window and Snake game state."""

    def __init__(self) -> None:
        super().__init__(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)
        arcade.set_background_color(BLACK)

        self.snake: list[tuple[int, int]] = []
        self.food: tuple[int, int] = (0, 0)
        self.direction = (1, 0)
        self.next_direction = (1, 0)
        self.elapsed = 0.0
        self.score = 0
        self.high_score = 0
        self.game_over = False
        self.game_state = "menu"
        self.menu_selection = 0
        self.snake_color_index = 0
        self.apple_color_index = 0

        self.score_text = arcade.Text(
            "Score: 0    High Score: 0",
            x=10,
            y=SCREEN_HEIGHT - 30,
            color=WHITE,
            font_size=16,
        )
        self.menu_title = arcade.Text(
            "SNAKE",
            x=SCREEN_WIDTH / 2,
            y=SCREEN_HEIGHT - 130,
            color=GREEN,
            font_size=48,
            anchor_x="center",
        )
        self.menu_instructions = arcade.Text(
            "UP/DOWN: choose    LEFT/RIGHT: change color    ENTER: play",
            x=SCREEN_WIDTH / 2,
            y=90,
            color=GRAY,
            font_size=14,
            anchor_x="center",
        )
        self.snake_option_text = arcade.Text("", x=250, y=330, font_size=22)
        self.apple_option_text = arcade.Text("", x=250, y=250, font_size=22)
        self.high_score_menu_text = arcade.Text(
            "",
            x=SCREEN_WIDTH / 2,
            y=SCREEN_HEIGHT - 180,
            color=WHITE,
            font_size=18,
            anchor_x="center",
        )
        self.game_over_text = arcade.Text(
            "Game Over",
            x=SCREEN_WIDTH / 2,
            y=SCREEN_HEIGHT / 2 + 20,
            color=RED,
            font_size=36,
            anchor_x="center",
        )
        self.restart_text = arcade.Text(
            "Press R to restart or M for menu",
            x=SCREEN_WIDTH / 2,
            y=SCREEN_HEIGHT / 2 - 25,
            color=WHITE,
            font_size=18,
            anchor_x="center",
        )

        self.update_menu_text()
        self.reset_game()

    @property
    def snake_color(self) -> tuple[int, int, int]:
        return SNAKE_COLORS[self.snake_color_index][1]

    @property
    def apple_color(self) -> tuple[int, int, int]:
        return APPLE_COLORS[self.apple_color_index][1]

    @property
    def active_snake_color(self) -> tuple[int, int, int]:
        """Use the selected snake color only after it has been unlocked."""
        selected = SNAKE_COLORS[self.snake_color_index]
        return selected[1] if selected[2] <= self.high_score else SNAKE_COLORS[0][1]

    @property
    def active_apple_color(self) -> tuple[int, int, int]:
        """Use the selected apple color only after it has been unlocked."""
        selected = APPLE_COLORS[self.apple_color_index]
        return selected[1] if selected[2] <= self.high_score else APPLE_COLORS[0][1]

    def reset_locked_colors_to_default(self) -> None:
        """Prevent locked menu choices from becoming active in a new round."""
        if SNAKE_COLORS[self.snake_color_index][2] > self.high_score:
            self.snake_color_index = 0
        if APPLE_COLORS[self.apple_color_index][2] > self.high_score:
            self.apple_color_index = 0

    def reset_game(self) -> None:
        """Start a new game inside the area below the score bar."""
        center_x = GRID_WIDTH // 2
        center_y = GRID_HEIGHT // 2
        self.snake = [
            (center_x, center_y),
            (center_x - 1, center_y),
            (center_x - 2, center_y),
        ]
        self.direction = (1, 0)
        self.next_direction = (1, 0)
        self.elapsed = 0.0
        self.score = 0
        self.game_over = False
        self.score_text.text = f"Score: 0    High Score: {self.high_score}"
        self.place_food()

    def place_food(self) -> None:
        """Place food in a free grid cell."""
        available_cells = [
            (x, y)
            for x in range(GRID_WIDTH)
            for y in range(GRID_HEIGHT)
            if (x, y) not in self.snake
        ]
        if available_cells:
            self.food = random.choice(available_cells)

    def update_menu_text(self) -> None:
        """Refresh menu labels after changing a color or high score."""
        self.snake_option_text.text = self.option_label(
            "Snake", SNAKE_COLORS, self.snake_color_index
        )
        self.apple_option_text.text = self.option_label(
            "Apple", APPLE_COLORS, self.apple_color_index
        )
        self.snake_option_text.color = self.snake_color
        self.apple_option_text.color = self.apple_color
        self.high_score_menu_text.text = f"High score: {self.high_score}"

    def option_label(
        self,
        title: str,
        options: list[tuple[str, tuple[int, int, int], int]],
        index: int,
    ) -> str:
        """Create a menu label showing the selected color and unlock status."""
        name, _, unlock_score = options[index]
        locked = unlock_score > self.high_score
        status = f"(Locked - High Score {unlock_score})" if locked else ""
        selected_row = 0 if title == "Snake" else 1
        marker = ">" if self.menu_selection == selected_row else " "
        return f"{marker} {title} color: {name} {status}"

    def on_draw(self) -> None:
        self.clear()
        if self.game_state == "menu":
            self.draw_menu()
            return

        self.draw_game()

    def draw_menu(self) -> None:
        """Draw the color-selection menu."""
        self.menu_title.draw()
        self.high_score_menu_text.draw()
        self.snake_option_text.draw()
        self.apple_option_text.draw()
        self.menu_instructions.draw()

        arcade.draw_rect_filled(arcade.rect.XYWH(190, 340, 30, 30), self.snake_color)
        arcade.draw_rect_filled(arcade.rect.XYWH(190, 260, 30, 30), self.apple_color)

    def draw_game(self) -> None:
        """Draw the score bar and game board."""
        # The wall sits directly beneath the score bar. The snake cannot enter
        # the reserved top area where the score text is displayed.
        board_top = SCREEN_HEIGHT - SCORE_BAR_HEIGHT
        arcade.draw_line(0, board_top, SCREEN_WIDTH, board_top, GRAY, 2)

        for x, y in self.snake:
            arcade.draw_rect_filled(
                arcade.rect.XYWH(
                    x * CELL_SIZE + CELL_SIZE / 2,
                    y * CELL_SIZE + CELL_SIZE / 2,
                    CELL_SIZE - 2,
                    CELL_SIZE - 2,
                ),
                self.active_snake_color,
            )

        food_x, food_y = self.food
        arcade.draw_rect_filled(
            arcade.rect.XYWH(
                food_x * CELL_SIZE + CELL_SIZE / 2,
                food_y * CELL_SIZE + CELL_SIZE / 2,
                CELL_SIZE - 2,
                CELL_SIZE - 2,
            ),
            self.active_apple_color,
        )

        self.score_text.draw()

        if self.game_over:
            self.game_over_text.draw()
            self.restart_text.draw()

    def on_update(self, delta_time: float) -> None:
        if self.game_state != "playing" or self.game_over:
            return

        self.elapsed += delta_time
        if self.elapsed < MOVE_INTERVAL:
            return
        self.elapsed -= MOVE_INTERVAL

        self.direction = self.next_direction
        head_x, head_y = self.snake[0]
        direction_x, direction_y = self.direction
        new_head = (head_x + direction_x, head_y + direction_y)

        hit_wall = not (
            0 <= new_head[0] < GRID_WIDTH and 0 <= new_head[1] < GRID_HEIGHT
        )
        hit_self = new_head in self.snake[:-1]
        if hit_wall or hit_self:
            self.game_over = True
            return

        self.snake.insert(0, new_head)
        if new_head == self.food:
            self.score += 1
            self.high_score = max(self.high_score, self.score)
            self.score_text.text = f"Score: {self.score}    High Score: {self.high_score}"
            self.update_menu_text()
            self.place_food()
        else:
            self.snake.pop()

    def cycle_color(
        self,
        options: list[tuple[str, tuple[int, int, int], int]],
        current_index: int,
        step: int,
    ) -> int:
        """Move through every color, including locked colors."""
        return (current_index + step) % len(options)

    def on_key_press(self, key: int, modifiers: int) -> None:
        if self.game_state == "menu":
            if key in (arcade.key.ENTER, arcade.key.SPACE):
                self.reset_locked_colors_to_default()
                self.update_menu_text()
                self.game_state = "playing"
                self.reset_game()
                return
            if key in (arcade.key.UP, arcade.key.W, arcade.key.DOWN, arcade.key.S):
                self.menu_selection = 1 - self.menu_selection
                self.update_menu_text()
                return
            if key in (
                arcade.key.LEFT,
                arcade.key.A,
                arcade.key.RIGHT,
                arcade.key.D,
            ):
                step = -1 if key in (arcade.key.LEFT, arcade.key.A) else 1
                if self.menu_selection == 0:
                    self.snake_color_index = self.cycle_color(
                        SNAKE_COLORS, self.snake_color_index, step
                    )
                else:
                    self.apple_color_index = self.cycle_color(
                        APPLE_COLORS, self.apple_color_index, step
                    )
                self.update_menu_text()
            return

        if key == arcade.key.M:
            self.game_state = "menu"
            self.update_menu_text()
            return
        if key == arcade.key.R and self.game_over:
            self.reset_game()
            return
        if self.game_over:
            return

        directions = {
            arcade.key.UP: (0, 1),
            arcade.key.W: (0, 1),
            arcade.key.DOWN: (0, -1),
            arcade.key.S: (0, -1),
            arcade.key.LEFT: (-1, 0),
            arcade.key.A: (-1, 0),
            arcade.key.RIGHT: (1, 0),
            arcade.key.D: (1, 0),
        }
        new_direction = directions.get(key)
        if new_direction is None:
            return

        # Prevent the snake from reversing into itself.
        if new_direction != (-self.direction[0], -self.direction[1]):
            self.next_direction = new_direction


def main() -> None:
    SnakeGame()
    arcade.run()


if __name__ == "__main__":
    main()
